import 'package:mtn_sa_revamp/files/utility/string.dart';

Map<String, String> brBR = {
  testStr: "ကုဒ်နံပါတ်",
  aboutStr: "၀န်ဆောင်မှု အကြောင်း",
  homeStr: "မူလစာမျက်နှာ",
  faqStr: "အမေးများသောမေးခွန်းများ",
  englishStr: "အင်္ဂလိပ်", //'English', //
  burmeseStr: "မြန်မာ", //"Burmese",//
  transactionTypeStr: "ငွေပေးချေမှု အမျိုးအစား",
  channelStr: "ချန်နယ်လိုင်း",
  historyStr: "မှတ်တမ်း",
  playStr: "နားဆင်မည်",
  previewTuneStr: "အစမ်းတေးသွား",
  seeMoreStr: "ပိုမိုကြည့်ရှုရန်",
  playingStr: "နားဆင်နေသည်",
  myTuneStatusStr: 'MyTune အခြေအနေ',
  expireDateStr: 'သက်တမ်းကုန်လွန်သွားသော',
  suspendStr: 'ခေတ္တရပ်နားမည်',
  activeStr: 'ဝန်ဆောင်မှု ရယူထားသည်',
  packNameStr: "ပက်ကေ့ခ်ျအမည်",
  unSubscribeStr: 'ဝန်ဆောင်မှုကို ပယ်ဖျက်မည်',
  reverseRBTStatusStr: 'မိမိရွေးချယ်ထားသောတေးသွားအခြေအနေ',
  settingStr: "ချိန်ညှိချက်မျာ:",
  tunesStr: "တေးသွားများ",
  signinStr: "အကောင့်သို့ဝင်မည်",
  setYourTunesStr: "တေးသွားသတ်မှတ်မည်",
  musicBundleStr: "သီချင်းအတွဲ ",
  customiseYourTunesStr: "တေးသွားများကိုစိတ်ကြိုက်ပြင်ဆင်မည်",
  profileTunesStr: "ကိုယ်ပိုင်တေးသွားများ",
  statusStr: "အခြေအနေ",
  callersStr: "ခေါ်ဆိုသူများ",
  playAtStr: "မှာနားဆင်မည်",
  fulldayStr: "တစ်ရက်စာ",
  allStr: "အားလုံး",
  noneStr: "မရှိ",
  monthlyStr: "လစဉ်",
  yearlyStr: "နှစ်စဉ်",
  fromTimeStr: "အချိန်မှ",
  toTimeStr: "အချိန်ထိ",
  fromDateStr: "ရက်မှ",
  toDateStr: "ရက်ထိ",
  advancedSettingsStr: "အဆင့်မြင့်သောဆက်တင်များ",
  selectTimeTypeStr: "အချိန်ရွေးချယ်မည်",
  fullDay24HourStr: "တစ်ရက်စာ - ၂၄ နာရီ",
  selecteTimeStr: "အချိန်ရွေးချယ်မည်",
  selectRepeatStr: "ပြန်လည်နားဆင်မည်",
  sunStr: "တနင်္ဂနွေနေ့",
  monStr: "တနင်္လာနေ့",
  tueStr: "အင်္ဂါနေ့",
  wedStr: "ဗုဒ္ဓဟူးနေ့",
  thusStr: "ကြာသပတေးနေ့",
  friStr: "သောကြာနေ့",
  satStr: "စနေနေ့",
  sStr: "တနင်္ဂနွေ",
  mStr: "တင်္နလာ",
  tuStr: "အင်္ဂါ",
  wStr: "ဗုဒ္ဓဟူး",
  tStr: "ကြာသပတေး",
  fStr: "သောကြာ",
  saStr: "စနေ",
  songStr: "သီချင်း",
  singerStr: "အဆိုတော်",
  codeStr: "ကုဒ်နံပါတ်",
  allCallerStr: "ခေါ်ဆိုသူအားလုံး",
  specificCallerStr: "အထူးဖုန်းခေါ်ဆိုသူ",
  callerGroupStr: "ခေါ်ဆိုသူအဖွဲ့",
  whomYouWantToPlayItStr: "မည်သူ့ကို နားဆင်စေလိုသနည်း ",
  whenYouWantToPlayItStr: "မည်သည့်အချိန်တွင် နားဆင်လိုသနည်း",
  startTimeStr: "စတင်ချိန်",
  endTimeStr: "ပြီးဆုံးချိန်",
  repeatStr: "ပြန်လည်နားဆင်မည်",
  pleaseEnterFriendNumberStr: "သင့်မိတ်ဆွေ၏ဖုန်းနံပါတ်ထည့်သွင်းပါ",
  addNuberStr: "နံပါတ်",
  enterNuberStr: "နံပါတ်ဖြည့်သွင်းမည်",
  shuffleStr: "ကျပန်း",
  customStr: "စိတ်ကြိုက်",
  noActivePlanStr: "ရယူထားသော၀န်ဆောင်မှုမရှိပါ",
  buyStr: "၀ယ်ယူမည်",
  userNameStr: "အသုံးပြုသူအမည်",
  preferenceStr: "ကြိုက်နှစ်သက်ရာများ",
  mobileNumberStr: "ဖုန်းနံပါတ်",
  subscribeStr: "စာရင်းသွင်းမည်",
  profileStr: "ကိုယ်ရေးအချက်အလက်",
  wishlistStr: "နားဆင်ချင်သည့်တေးသွားများ",
  deleteStr: "ပယ်ဖျက်မည်",
  timeBaseStr: "အချိန်ရွေးချယ်မည်",
  repeatBaseStr: "ပြန်လည်နားဆင်မည်",
  featureIsAvailableForLoggedInStr: "ဤ၀န်",
  giftStr: "လက်ဆောင်",
  shareStr: "မျှဝေမည်",
  logoutStr: "ထွက်မည်",
  okStr: "အိုကေ",
  verifyOTPStr: "တစ်ခါသုံးကုဒ်နံပါတ်ကိုအတည်ပြုပါ",
  successFullyLoggedInStr: "၀င်ရောက်မှုအောင်မြင်ပါသည်",
  someThingWentWrongStr: "တစ်ခုခုမှားယွင်းနေပါသည်",
  enterValidMsisdnStr: "ကျေးဇူးပြု၍မှန်ကန်သောဖုန်းနံပါတ်အားဖြည့်သွင်းပါ",
  enterValidOtpStr: "ကျေးဇူးပြု၍မှန်ကန်သောတစ်ခါသုံးကုတ်နံပါတ်အားဖြည့်သွင်းပါ ",
  bothMsisdnCanBeSameStr: "အကောင့်၀င်ထားသောနံပါတ်နှင့်တူညီမှုမရှိရပါ",
  enterMobileNumberStr: "ဖုန်းနံပါတ်ဖြည့်သွင်းမည်",
  countryCodeStr: "+95",
  myAccountStr: "ကိုယ်ပိုင်အကောင့်",
  cancelStr: "ပယ်ဖျက်မည်",
  editStr: "ပြင်ဆင်မည်",
  saveStr: "သိမ်းဆည်းမည်",
  viewStr: "ကြည့်ရှုမည်",
  selectAtleastOneCatStr: "အနည်းဆုံး အမျိုးအစားတစ်ခုကိုရွေးချယ်ပါ",
  confirmStr: "အတည်ပြုမည်",
  tuneChargeStr: "တေးသွားကျသင့်ငွေ",
  buyTuneStr: "တေးသွား၀ယ်ယူမည်",
  tuneStr: "တေးသွားများ",
  tuneCodeStr: "တေးသွားကုဒ်",
  noTransactionFoundStr: "၀ယ်ယူ၍မရပါ",
  bannerDetailStr: "ဘန်နာအသေးစိတ်",
  tuneListEmptyStr: "တေးသွားစာရင်းမရှိပါ",
  searchTuneStr: "တေးသွားရှာဖွေမည်",
  artistListEmptyStr: "အဆိုတော်စာရင်းမရှိပါ",
  artistStr: "အဆိုတော်",
  myTuneLocationStr: "My Tune တည်နေရာ",
  searchedResultForStr: "ရလဒ်များရှာဖွေမည် ",
  loginStr: "ဝင်ရောက်မည်",
  companyStr: "ကုမ္ပဏီ",
  contactusStr: "ဆက်သွယ်ရန်",
  fallowUsStr: "ကျွန်ုပ်တို့ကို ဖောလိုးထားပါ",
  helpStr: "အကူအညီ",
  copyRightStr: "၂၀၂၀ မူပိုင်ခွင့် မူပိုင်ခွင့်များကိုလက်၀ယ်ထားသည်",
  privacyStr: "ကိုယ်ရေးအချက်အလက်များ",
  termsStr: "စည်းကမ်းသတ်မှတ်ချက်များ",
  pleaseEnterMsisdn: "ကျေးဇူးပြု၍ဖုန်းနံပါတ်အားဖြည့်သွင်းပါ",
  pleaseEnterValidMsisdnStr: "ကျေးဇူးပြု၍မှန်ကန်သောဖုန်းနံပါတ်အားဖြည့်သွင်းပါ",
  pleaseEnterOtp: "ကျေးဇူးပြု၍တစ်ခါသုံးကုဒ်နံပါတ်အားဖြည့်သွင်းပါ",
  pleaseEnterAValidOtpStr:
      "ကျေးဇူးပြု၍မှန်ကန်သောတစ်ခါသုံးကုဒ်နံပါတ်အားဖြည့်သွင်းပါ",
  whatrLookingForStr: "ဘာကိုရှာနေတာလဲ ?",
  express: "သင့်ရဲ့ခံစားချက်များကိုဖော်ပြလိုက်ပါ",
  homeInfo1: 'သင်ဘာကိုရှာဖွေနေပါသလဲ',
  homeInfo2:
      'မိတ်ဆွေထံဖုန်းခေါ်ဆိုသူများသည် မိတ်ဆွေရယူထားသော တေးသွားများကို ဖုန်းခေါ်ဆိုမှုပြုလုပ်နေစဉ်အတွင်းနားဆင်ရမည်ဖြစ်သည်',
  homeInfo3: 'လစဉ်၀န်ဆောင်ခအတွက် ရက် (၃၀) လျှင် ၉၅၀ ကျပ်ကျသင့်မည်ဖြစ်သည်',
  homeInfo4:
      '၀န်ဆောင်မှုအား ရက် (၃၀) ကြာပြီးနောက်အလိုအလျောက်သက်တမ်းတိုးသွားမည်ဖြစ်သည်',
  homeInfo6: 'အကန့်အသတ်ဖြင့်ပြန်လည်ရယူနိုင်သည်',
  signInToYourAccountStr: "သင်၏အကောင့်သို့၀င်မည်",
  pleaseEnterYourMobileNumberInOrderToAuthenticateStr:
      "ကျေးဇူးပြု၍မိတ်ဆွေ၏ဖုန်းနံပါတ်ကိုအတည်ပြုရန်အတွက် ဖြည့်သွင်းပါ",
  requestOTPStr: "တစ်ခါသုံးကုဒ်နံပါတ်တောင်းခံမည်",
  signupAgreementStr: "အကောင့်၀င်ခြင်းဖြင့်  သင်သည်ကျွန်ုပ်တို့၏ ",
  termsAndPolicyStr:
      "အသုံးပြုမှုဆိုင်ရာစည်းမျဉ်းများနှင့် ကိုယ်ရေးကိုယ်တာမူဝါဒများကို သဘောတူညီမည်ဖြစ်သည်",
  enter6DigitOtpStr: "ဂဏန်း (၆) လုံးပါသောတစ်ခါသုံးကုဒ်နံပါတ်အားဖြည့်သွင်းပါ",
  oneTimePasswordHasBeenSentStr: "တစ်ခါသုံးကုတ်နံပါတ်အားသင့်ထံပို့လိုက်ပါပြီ ",
  currentlyPlayingToMyCallerStr: "သင့်ထံဖုန်းခေါ်ဆိုသူများ နားဆင်နေပါသည်",
  howToPlaySelectedTunesToYourCallersStr:
      "သင့်ထံဖုန်းခေါ်ဆိုသူများအား ရွေးချယ်ထားသည့် တေးသွားများကိုမည်ကဲ့သို့ နားဆင်စေမည်နည်း။ ပိုမိုသိရှိရန် >",
  chooseSubscriptionPlanStr: "စာရင်းသွင်းမှုပလန်ကိုရွေးချယ်ပါ",
  youShouldSubscribeAPlanStr:
      "တေးသွားများကိုမ၀ယ်ယူခင် သို့မဟုတ် လက်ဆောင်မပေးခင် သင့်အနေဖြင့် ၀န်",
  myTuneLocationValueStr:
      "နံပါတ် (၂၂၁) ၊ အလွှာ (၁၇-၂၂-၂၃)  ဆူးလေဘုရားလမ်း ကျောက်တံတားမြို့နယ် ရန်ကုန်မြို့ ၁၁၁၈၂ မြန်မာ",
  tuneSuffleOnMessageStr:
      "သင်၏ကျပန်းတေးသွားသည်ပိတ်သွားမည်ဖြစ်ပြီး သင့်ထံဖုန်းခေါ်ဆိုသူများသည် နောက်ဆုံးတေးသွားကိုသာ နားဆင်ရမည်ဖြစ်သည်။ သင်၏အဆင့်မြင့်သောချိန်ညှိမှုများမှာ မပြောင်းလဲပဲရှိနေမည်ဖြစ်သည်",
  tuneSuffleOffMessageStr: "ကျပန်းတေးသွားကို ဖွင့်လိုပါသလား",
  languageChangeConfirmMessageStr: "ဘာသာစကားပြောင်းရန် သေချာပါသလား",
  resumeStr: "ပြန်လည်စတင်မည်",
  yourServiceIsCurrentlyRunningStr: "သင်၏၀န်ဆောင်မှုကို အသုံးပြုနေပါသည်",
  yourServiceIsNotCurrentlyRunningStr:
      "သင်၏၀န်ဆောင်မှုကိုခေတ္တရပ်နားလိုက်ပါပြီ",
  notSubscribedToAnyService: "သင်သည် mytune ၀န်ဆောင်မှုကိုရယူထားခြင်းမရှိပါ",

//--------------------------------------

  myTuneStr: "My Tunes",
  activateStr: 'Activate',
  addToShuffleStr: "Add to Suffle",
  musicPackageStr: "Music Package",
  madeWithStr: "Made with",
  homeInfo5: 'Tone price at 37.07 SDG valid per month',
  inActiveStr: 'InActive',
  sessionExpiredStr:
      'Session expired.\n You will be logged out and redirected to Home page.',
  changeStatusConfirmMessageStr: "Are you sure you want to change Status?",
  unSubscribeConfirmMessageStr: "Are you sure you want to unsubscribe?",
  notActiveSubscriberMessageStr: "You are not an active subscriber",
  areYouSureYouWantToDeleteStr: "Are you sure you want to delete?",
  sentOtpInTimeStr: "Resent Otp in ",
  sentOtpStr: "Resent Otp",
  pleaseActivateToUnsubscribeStr:
      "Please activate your pack before unsubscribing.",
  playingTuneStr: "My Playing Tunes",
  myRrbtTunesStr: "My RRBT Tunes",
  crbtStr: "CRBT",
  rrbtStr: "RRBT",
  myRrbtTunes: "My RRBT tunes",
  musicPackStr: "Music Box",
  upgradeMessageStr:
      'Upgrade to EAUC at Kyat 100/1 day and enjoy unlimited tunes',
  nameTuneStr: "Name Tunes",
  musicPackInfo1:
      "You can enjoy with Three famous Tunes together in one package.\n- Three selected tunes includes in each package.\n- Available Four Music Packages by the selected famous singers: Myo Gyi, Sai Sai Kham Leng, R Zar Ni and Ni Ni Khin Zaw.\n- Muisc Package price 787.50 Kyats and each tune is valid for 30 days.",
  musicPackInfo2: """How to buy the music package:
To buy Myo Gyi Package: Send MP 55595001 to 333
Available tunes on Music Package: Min Shid Tae Myot, Pyan Lar Chein Lay, Myit Tar Tayar

To buy Sai Sai Kham Leng Package: Send MP 55595003 to 333
Available tunes on Music Package: Thu Ngal Chin, Char Tate A Twat, Yee Sar Sar""",
  musicPackInfo3: """To buy R Zar Ni Package: Send MP 55595004 to 333
Available tunes on Music Package: Min Thar Shi Yin, Yoe Thar Swar Khit Nyout Kya Thu Myer, Kabar Thar

To buy Ni Ni Khin Zaw Package: Send MP 55595002 to 333
Available tunes on Music Package: Thit Sar Ma Pyat Kyae , Yat Sat Thwar Thu, Myaw Lint Chat Ta Sone Ta Yar""",
};
