import 'package:mtn_sa_revamp/files/utility/string.dart';

Map<String, String> enUS = {
  testStr: "Testing string",
  myTuneStr: "My Tunes",
  aboutStr: "About",
  homeStr: "Home",
  faqStr: "FAQ",
  englishStr: "English",
  burmeseStr: "Burmese",
  transactionTypeStr: "Transaction Type",
  channelStr: "Channel",
  historyStr: "History",
  playStr: "Play",
  previewTuneStr: "Preview Tune",
  seeMoreStr: "See More",
  playingStr: "Playing",
  myTuneStatusStr: 'MyTune Status',
  expireDateStr: 'Expired',
  suspendStr: 'Suspend',
  activeStr: 'Active',
  activateStr: 'Activate',
  packNameStr: "Pack Name",
  unSubscribeStr: 'UNSUBSCRIBE',
  reverseRBTStatusStr: 'Reverse RBT Status',
  settingStr: "Setting",
  tunesStr: "Tunes",
  signinStr: "SignIn",
  setYourTunesStr: "Set your tunes",
  musicBundleStr: "Music Bundle",
  customiseYourTunesStr: "Customise your tunes",
  profileTunesStr: "Profile Tunes",
  statusStr: "Status",
  callersStr: "Callers",
  playAtStr: "Play at",
  fulldayStr: "FullDay",
  allStr: "All",
  noneStr: "None",
  monthlyStr: "Monthly",
  yearlyStr: "Yearly",
  fromTimeStr: "From Time",
  toTimeStr: "To Time",
  fromDateStr: "From Date",
  toDateStr: "To Date",
  advancedSettingsStr: "Advanced Settings",
  selectTimeTypeStr: "Select Time Type",
  fullDay24HourStr: "Full Day - 24 hr",
  selecteTimeStr: "Select Time",
  selectRepeatStr: "Select Repeat",
  sunStr: "Sun",
  monStr: "Mon",
  tueStr: "Tue",
  wedStr: "Wed",
  thusStr: "Thus",
  friStr: "Fri",
  satStr: "Sat",
  sStr: "S",
  mStr: "M",
  tuStr: "T",
  wStr: "W",
  tStr: "T",
  fStr: "F",
  saStr: "S",
  songStr: "Song",
  singerStr: "Singer",
  codeStr: "Code",
  allCallerStr: "All Callers",
  specificCallerStr: "Callers Group",
  callerGroupStr: "Specific Caller",
  whomYouWantToPlayItStr: "Whom You Want To Play It?",
  whenYouWantToPlayItStr: "When You Want To Play It?",
  startTimeStr: "Start Time",
  endTimeStr: "End Time",
  repeatStr: "Repeat",
  pleaseEnterFriendNumberStr: "Please enter friend number.",
  addNuberStr: "Add Number",
  enterNuberStr: "Enter Number",
  shuffleStr: "Shuffle",
  customStr: "Custom",
  noActivePlanStr: "No Active Plan",
  buyStr: "Buy",
  userNameStr: "User Name*",
  preferenceStr: "Preference*",
  mobileNumberStr: "Mobile number",
  subscribeStr: "Subscribe",
  profileStr: "Profile",
  wishlistStr: "Wishlist",
  deleteStr: "Delete",
  timeBaseStr: "Select time base",
  repeatBaseStr: "Select repeat",
  featureIsAvailableForLoggedInStr:
      "This feature is availabe for logged in users",
  giftStr: "Gift",
  shareStr: "Share",
  logoutStr: "Logout",
  okStr: "Ok",
  verifyOTPStr: "Verify OTP",
  successFullyLoggedInStr: "Login Successful",
  someThingWentWrongStr: "Some thing went wrong",
  enterValidMsisdnStr: "Please enter a valid msisdn.",
  enterValidOtpStr: "Please enter a valid OTP.",
  bothMsisdnCanBeSameStr: "Number cannot be same as the logged in number",
  enterMobileNumberStr: "Enter Mobile Number",
  countryCodeStr: "+95",
  myAccountStr: "My Account",
  cancelStr: "Cancel",
  editStr: "Edit",
  saveStr: "Save",
  viewStr: "View",
  selectAtleastOneCatStr: "Select at least one category.",
  confirmStr: "Confirm",
  tuneChargeStr: "Tune Charge",
  buyTuneStr: "Buy Tune",
  tuneStr: "Tunes",
  tuneCodeStr: "Tone Code",
  noTransactionFoundStr: "No Transaction found",
  bannerDetailStr: "Banner Detail",
  tuneListEmptyStr: "Tune list empty",
  searchTuneStr: "Search Tune",
  artistListEmptyStr: "Artist list empty",
  artistStr: "Artist",
  myTuneLocationStr: "My Tune | Location",
  searchedResultForStr: "Search result for ",
  loginStr: "Login",
  companyStr: "Company",
  contactusStr: "Contact Us",
  fallowUsStr: "Follow Us On",
  helpStr: "Help",
  copyRightStr: "© 2020 Copyright. All Rights Reserved",
  privacyStr: "Privacy Policy",
  termsStr: "Terms and conditions",
  pleaseEnterMsisdn: "Please enter msisdn",
  pleaseEnterValidMsisdnStr: "Please enter valid msisdn",
  pleaseEnterOtp: "Please enter Otp",
  pleaseEnterAValidOtpStr: "Please enter a Valid Otp",
  whatrLookingForStr: "What are you looking for?",
  express: "Express Your Moods",
  homeInfo1: 'What are you looking for?',
  homeInfo2: 'Callers will listen to the ringback tone that you set',
  homeInfo3: 'Monthly Subscription fee of 59.18 SDG for 30 days',
  homeInfo4: 'Subscription will be renewed after 30 days',
  homeInfo5: 'Tone price at 37.07 SDG valid per month',
  homeInfo6: 'Limited fallback available',
  signInToYourAccountStr: "Sign in to your Account",
  pleaseEnterYourMobileNumberInOrderToAuthenticateStr:
      "Please enter your mobile number in order to Authenticate",
  requestOTPStr: "Request OTP",
  signupAgreementStr: "By Signing up you will be agree to our",
  termsAndPolicyStr: "Terms of use & Privacy Policy",
  enter6DigitOtpStr: "Enter 6 Digit OTP",
  oneTimePasswordHasBeenSentStr: "One Time Password (OTP) has been sent to ",
  currentlyPlayingToMyCallerStr: "Currently Playing To My Caller",
  howToPlaySelectedTunesToYourCallersStr:
      "How to play selected tunes to your callers? Learn More >",
  chooseSubscriptionPlanStr: "Choose your Subscription Plan",
  youShouldSubscribeAPlanStr:
      "You should subscribe a plan before you buy or gift tunes",
  myTuneLocationValueStr:
      "No.221, Level 17-22-23,\nSule Pagoda Road,\nKyauktada Township,\nYangon, 11182 Myanmar",
  tuneSuffleOnMessageStr:
      "Your suffle will be disabled and your callers will only listen to the latest tune. Your advance settings will remain unaffected.",
  tuneSuffleOffMessageStr: "Do you want to enable suffle?",
  languageChangeConfirmMessageStr: "Are you sure you want to change language?",
  resumeStr: "Resume",
  yourServiceIsCurrentlyRunningStr: "Your service is currently running.",
  yourServiceIsNotCurrentlyRunningStr:
      "You have temporarily suspended your  service.",
  notSubscribedToAnyService: "You are not subscribed to mytune service.",
  inActiveStr: 'InActive',
  sessionExpiredStr:
      'Session expired.\n You will be logged out and redirected to Home page.',
  changeStatusConfirmMessageStr: "Are you sure you want to change Status?",
  unSubscribeConfirmMessageStr: "Are you sure you want to unsubscribe?",
  notActiveSubscriberMessageStr: "You are not an active subscriber",
  areYouSureYouWantToDeleteStr: "Are you sure you want to delete?",
  sentOtpInTimeStr: "Resent Otp in ",
  sentOtpStr: "Resent Otp",
  pleaseActivateToUnsubscribeStr:
      "Please activate your pack before unsubscribing.",
  nameTuneStr: "Name Tunes",
};
