String privacyHeaderString = """Privacy Policy""";

String privacySubTitle =
    """This website is owned and operated by ATOM Myanmar Limited (hereinafter referred to as "ATOM Myanmar” "Site" "us" "we" or "our"), we are committed to safeguarding the privacy of our website visitors, this policy sets out how we will treat your personal information.""";
String pricacyInfo =
    """The Privacy Policy applies to all Visitors, Customers, Buyers and Users (collectively referred to as "Users".) In addition, this Privacy Policy applies to these services provided by this Site. This Privacy Policy describes how we handle your personal information for our services on the websites. It applies generally to the website and content and other related websites where this Policy appears in the footer of the page. ATOM Myanmar websites or relevant websites we operate through our Vendors/Suppliers/Partners may be governed by separate Privacy Policies. Ideally, these privacy practices are similar to those described in this Privacy Policy. We will try to provide you with adequate information so you can make an informed decision whether to visit these websites and whether during registration you wish to voluntarily provide any personal information, e.g., your mobile number. Subject to the requirements of applicable law, we strive to provide a consistent set of privacy practices throughout the website trading community. By accepting the Privacy Policy and the Terms & Conditions during registration, you expressly consent to our collection, storage, use and disclosure of your personal information as described in this Privacy Policy. This Privacy Policy should read in conjunction with the terms and conditions of this website. Our Disclosure of Your Information.
We may disclose personal information to respond to legal requirements, enforce our policies, respond to claims that a listing or other content violates the rights of others, or protect anyones rights, property, or safety. Such information will be disclosed in accordance with applicable laws and regulations of the Country. Information You Share on https://mytune.atom.com.mm Your Log In Password is displayed while you log in to https://mytune.atom.com.mm (so will not be available to the public), and is connected to all of your activity in this site. Other people cant see your activity (e.g. your order, purchase list) or other information unless you agree so electronically. Your feedback, ratings and associated comments may be displayed for the enhancement of the website and in-depth understanding for other visitors. If you access our sites from a shared computer or a computer in an internet café, certain information about you, such as your log in password, activity or reminders fr this website, may also be visible to other individuals who use the computer after you.
Using Information from https://mytune.atom.com.mm
We encourage you not to disclose your privacy practices and respect the privacy of other users. Though, we guarantee the privacy or security of your information but always suggest you to be updated by yourself on the privacy and security of your information but always suggest you to be updated by yourself on the privacy and security policies of this website and its affiliated sites before entering into a transaction and choosing to share your information.
For more information on how ATOM Myanmar will process your personal data is available https://mytune.atom.com.mm/CRBT_TELENOR/PopulateSongs/mytune.atom.com.mm.""";

String privacyHeaderStringBr =
    """ပုဂ္ဂိုလ်ရေးအချက်အလက် လုံခြုံမှုဆိုင်ရာထိန်းသိမ်းမှုပေါ်လစီ""";

String privacySubTitleBr =
    """ဤဝက်ဘ်ဆိုက်ကို ATOM Myanmar Limited (ဤမှနောင်တွင် "ATOM Myanmar” “အက်တမ်မြန်မာ” "ဆိုက်" "ကျွန်ုပ်တို့ကို/၏" "we" or "our" ဟု ရည်ညွှန်းသုံးနှုန်းသွားမည်)၊ မှ ပိုင်ဆိုင်၍ စီမံခန့်ခွဲ လည်ပတ်လုပ်ကိုင်ဆောင်ရွက်လျှက်ရှိပြီး၊ ကျွန်ုပ်တို့၏ ဝက်ဘ်ဆိုက်သို့ ဝင်ရောက်လည်ပတ်ကြည့်ရှုသူများ၏ ပုဂ္ဂိုလ်ရေးအချက်အလက်များကို ကာကွယ်သွားရန် သန္နိဌာန်ချမှတ်ထားသည့်အားလျှော်စွာ လူကြီးမင်း၏ ပုဂ္ဂိုလ်ရေးအချက်အလက်များကို ကျွန်ုပ်တို့က မည်သို့မည်ပုံ ကိုင်တွယ်ဆောင်ရွက်သွားမည်ဆိုသည်ကို ဤပေါ်လစီက ချမှတ်ပေးပါသည်။""";
String pricacyInfoBr =
    """ယင်းတို့အပြင်၊ ဤ ပုဂ္ဂိုလ်ရေးအချက်အလက် လုံခြုံမှုဆိုင်ရာထိန်းသိမ်းမှုပေါ်လစီ သည် ဤဆိုက်မှ ပေးအပ်လျှက်ရှိသည့် ဝန်ဆောင်မှုအားလုံးနှင့် သက်ဆိုင်အကျုံးဝင်ပါသည်။ ဝက်ဘ်ဆိုက်ပေါ်မှ ကျွန်ုပ်တို့၏ဝန်ဆောင်မှုများအတွက် လူကြီးမင်းတို့၏ ဤကိုယ်ရေးကိုယ်တာ/ ပုဂ္ဂိုလ်ရေးအချက်အလက်တို့ကို ကျွန်ုပ်တို့က မည်သို့မည်ပုံ ကိုင်တွယ်ဆောင်ရွက်သည်ဆိုသည့် ကိစ္စရပ်များနှင့်စပ်လျဉ်း၍ လုံခြုံရေးပေါ်လစီက ဖော်ပြပေးပါသည်။ ‌‌ဝက်ဘ်ဆိုက်၊ ပါဝင်သည့်အကြောင်းအရာနှင့် စာမျက်နှာအောက်ခြေတွင် ဤပေါ်လစီကို ရေးသားဖော်ပြထားသည့် အခြားသော ဆက်စပ်ဝက်ဘ်ဆိုက်များနှင့် ဤပေါ်လစီသည် ယေဘုယျအားဖြင့် သက်ဆိုင်အကျုံးဝင်ပါသည်။ အက်တမ်မြန်မာ ဝက်ဘ်ဆိုက်များ သို့မဟုတ် ကျွန်ုပ်တို့၏ ပေးသွင်းသူ/အဝယ်တော်/မိတ်ဖက်လုပ်ငန်းများမှတဆင့် ကျွန်ုပ်တို့ စီမံဆောင်ရွက်လုပ်ကိုင်လျှက်ရှိသည့် သက်ဆိုင်ရာဝက်ဘ်ဆိုက်များသည် သီးခြား ပုဂ္ဂိုလ်ရေးအချက်အလက် လုံခြုံမှုဆိုင်ရာ ထိန်းသိမ်းမှုပေါ်လစီဖြင့် လွှမ်းမိုးသက်ရောက်ခြင်း ရှိနိုင်ပါသည်။ အထူးအားဖြင့် ပုဂ္ဂိုလ်ရေး‌ဆိုင်ရာအချက်အလက်လုံခြုံရေးဆိုင်ရာ ကျင့်သုံးပုံအလေ့အထတို့သည် ဤ ပုဂ္ဂိုလ်ရေးဆိုင်ရာ သတင်းအချက်အလက်များလုံခြုံရေး ပေါ်လစီနှင့် အတူတူပင်ဖြစ်သည်။ လူကြီးမင်းအနေဖြင့် ဤဝက်ဘ်ဆိုက်တို့ကို ဝင်ရောက်လည်ပတ်ကြည့်ရှုသင့်မသင့် နှင့် မှတ်ပုံတင်စဉ်အတွင်းတွင် လူကြီးမင်း၏ မည်သည့် ကိုယ်‌ရေးကိုယ်တာ/ပုဂ္ဂိုလ်ရေးသတင်းအချက်အလက်မဆို ဥပမာ၊ မိုဘိုင်းဖုန်းနံပါတ် ကို မိမိ၏ သဘောဆန္ဒအလျှောက် ပေးအပ်သင့်မသင့်ဆိုသည်များနှင့်စပ်လျဉ်း၍ ကောင်းစွာနားလည်သိရှိပြီး ဆုံးဖြတ်ချက်များကို ပြုလုပ်ချမှတ်နိုင်ရန်အလို့ငှာ ပြည့်စုံလုံလောက်သည့် သတင်းအချက်အလက်များကို ကျွန်ုပ်တို့က လူကြီးမင်းအား ပေးအပ်သွားပါမည်။ သက်ဆိုင်ရာ ဥပဒေများအရ လိုအပ်ချက်အပေါ်တွင်မူတည်၍ တစ်ပြေးညီတည်း/တစ်သမတ်တည်းဖြစ်သော ပုဂ္ဂိုလ်ရေးအချက်အလက်များ လုံခြုံမှုဆိုင်ရာ ကျင့်သုံးဆောင်ရွက်မှုအလေ့အထများကို အွန်လိုင်း/ဝက်ဘ်ဆိုက်များမှတဆင့် ကူးသန်းရောင်းဝယ်ဖောက်ကားမှုများကို ပြုလျက်ရှိကြသော အသိုက်အဝန်းများတွင် ကျွန်ုပ်တို့ပေးအပ်သွားနိုင်ရန် ကြိုးပမ်းအားထုတ်သွားပါမည်။ စာရင်းသွင်း မှတ်ပုံတင်ပြုလုပ်စဉ်တွင် ပုဂ္ဂိုလ်ရေးအချက်အလက် လုံခြုံမှုဆိုင်ရာထိန်းသိမ်းမှုပေါ်လစီ နှင့် စည်းကမ်းသတ်မှတ်ချက်တို့ကို လက်ခံသဘောတူလိုက်ခြင်းအားဖြင့် လူကြီးမင်းတို့၏ ပုဂ္ဂိုလ်ရေးဆိုင်ရာသတင်းအချက်အလက်များကို ကျွန်ုပ်တို့ ကောက်ယူစုဆောင်းမှု၊ သိုမှီး သိမ်းဆည်းထားရှိမှု၊ သုံးစွဲမှု နှင့် ဖွင့်ဟထုတ်ဖော် ပြောဆိုမှုတို့နှင့်စပ်လျဉ်း၍ ဤပေါ်လစီ မူဝါဒသဘောထားတွင် ရေးသားဖော်ပြထားသည့်အတိုင်း လူကြီးမင်းက အတိအလင်း သဘောတူညီပါသည်။ ဤကိုယ်ရေးကိုယ်တာ/ပုဂ္ဂိုလ်‌ရေးသတင်းအချက်အလက် လုံခြုံရေးပေါ်လစီကို ဤဝက်ဘ်ဆိုက်၏ စည်းကမ်းသတ်မှတ်ချက်များ နှင့် တွဲဖက်နားလည်ပြန်ဆိုဖတ်ရှုသင့်ပါသည်။ လူကြီးမင်း၏ သတင်းအချက်အလက်များကို ကျွန်ုပ်တို့ ဖွင့်ဟထုတ်ဖော်ပြောဆိုခြင်း

ဥပဒေရေးရာလိုအပ်ချက်များ၊ ကျွန်ုပ်တို့၏ မူဝါဒကို စည်းကြပ်ဆောင်ရွက်ရန်လိုအပ်ချက်များ၊ အခြားတစ်ပါးသူတို့၏ စာရင်းပြုစုထားရှိမှုများ သို့မဟုတ် အကြောင်းအရာပိုင်းအားဖြင့် အခြားတစ်ပါးသူတို့၏ အခွင့်အရေးကို ချိုးဖောက်လျက် ရှိသည်ဆိုသည့် တောင်းဆိုမှုများ သို့မဟုတ် အခြားသူများ၏ အခွင့်အရေးကို ကာကွယ်ပေးနိုင်ရန် သို့မဟုတ် တစ်စုံတစ်ဦး၏/တစ်ဦးဦး၏ အခွင့်အရေး၊ ပိုင်ဆိုင်မှု သို့မဟုတ် ဘေးကင်းလုံခြုံမှုကိုမဆို တုန့် ပြန်သည့်အနေဖြင့် လူကြီးမင်းတို့၏ ပုဂ္ဂိုလ်ရေးသတင်းအချက်အလက်များကို ကျွန်ုပ်တို့က ဖွင့်ဟထုတ်ဖော်ခြင်းပြုနိုင်သည်။ ယင်းကဲ့သို့သော သတင်းအချက်အလက်များကို နိုင်ငံတော်၏သက်ဆိုင်ရာ ဥပဒေများနှင့် နည်းဥပဒေ စည်းမျဉ်းစည်ကမ်းများနှင့်အညီသာလျှင် ဖွင့်ဟထုတ်ဖော်သွားပါမည်။ အပေါ်တွင် လူကြီးမင်း ဝေမျှသော အတင်းအချက်အလက်တို့နှင့် လူကြီးမင်း၏ လော့ဂ်အင် ဝင်သည့် စကားဝှက်တို့ကို ဖော်ပြပေး ထားပြီး (ယင်းတို့ကို အများပြည်သူတို့က ရရှိနိုင်မည်မဟုတ်ပါ) ဤဆိုက်ပေါ်တွင် လူကြီးမင်း၏ လှုပ်ရှားမှုများအားလုံးနှင့် ချိတ်ဆက်ထားပါသည်။ လူကြီးမင်း၏ လှုပ်ရှားမှုများ ( ဥပမာ၊ လူကြီးမင်း၏ အော်ဒါမှာယူမှု၊ ဝယ်ယူမှု စာရင်း) သို့မဟုတ် အခြားသော သတင်းအချက်အလက်များကို လူကြီးမင်းက သဘောတူညီခြင်းမရှိလျင် အခြားသူများက ကြည့်ရှု့နိုင်မည်မဟုတ်ပါ။ mytune.atom.com.mm ဝက်ဘ်ဆိုက်ကို ပိုမိုတိုးတက်ကောင်းမွန်စေရန် နှင့် ဝက်ဘ်ဆိုက်သို့ လာရောက်လည်ပတ်ကြည့်ရှု့ကြသည့် အခြားသူများအနေဖြင့် ပိုမိုနက်ရှိုင်းစွာ နားလည်သိရှိနိုင်စေရန် အလို့ငှာ လူကြီးမင်း၏ အကြံပြုချက်များ/ထင်မြင်ချက်ပေးခြင်းများ၊ အရည်အသွေးပိုင်း ပြည်စုံကောင်းမွန်မှုရှိခြင်းနှင့်စပ်လျဉ်း၍ အမှတ်ပေး ဖော်ပြချက်များ နှင့် ယင်းနှင့်ဆက်စပ်သက်ဆိုင်သည့် မှတ်ချက်များကို ပြသထားပါမည်။ အကယ်၍ လူကြီးမင်းသည် မျှဝေသုံးစွဲသည့် ကွန်ပြူတာ သို့မဟုတ် အင်တာနက် ကဖေးမှ ကွန်ပြူတာကို သုံး့စွဲ၍ ကျွန်ုပ်တို့၏ ဆိုက်များသို့ ဝင်ရောက်ပါက လူကြီးမင်း၏ လော့ဂ်အင် စကားဝှက်၊ လုပ်ဆောင်မှု သို့မဟုတ် ဤဝက်ဘ်ဆိုက်မှ အသိပေး နှိုးဆော်ချက်စာများအစရှိသော ဝင်ရောက်မှုဆိုင်ရာ အချို့သော သတင်းအချက်အလက်များကို လူကြီးမင်းသုံးစွဲပြီးသည့်နောက်တွင် ယင်းကွန်ပြူတာကို သုံးစွဲသည့် အခြားသောသူတို့ကလည်း တွေ့မြင် သိရှိနိုင်ပါသည်။

mytune.atom.com.mm ထံမှ သတင်းအချက်အလက်များကို သုံးစွဲခြင်း

လူကြီးမင်းအနေဖြင့် ပုဂ္ဂိုလ်ရေး အချက်အလက်လုံခြုံရေးဆိုင်ရာ အလေ့အထများကို ထုတ်ဖော် ပြောဆိုခြင်းမပြုရန် နှင့် အခြားသုံးစွဲသူများ၏ ကိုယ်ရေးကိုယ်တာ/ ပုဂ္ဂိုလ်ရေးအချက် အလက်များလုံခြုံရေးကို လေးစားသမှုရှိရန် ကျွန်ုပ်တို့က တိုက်တွန်းပါသည်။ လူကြီးမင်း၏ ပုဂ္ဂိုလ်ရေးသတင်းအချက်အလက် လုံခြုံမှုရှိရေးသို့မဟုတ် လုံခြုံရေးဆိုင်ရာများကို အာမခံသော်ငြားလည်း၊ လူကြီးမင်းအနေဖြင့် ဝယ်ယူရန်လုပ်ဆောင်ခြင်းမပြုမီ နှင့် လူကြီမင်း၏ သတင်းအချက်အလက်များကို မျှဝေရန် ‌ရွေးချယ်ဆောင်ရွက်ခြင်း မပြုမီ လူကြီးမင်း၏သတင်းအချက်အလက် မပေါက်ကြားစေရေး၊ လုံခြုံမှုရှိရေးတို့နှင့်စပ်လျဉ်း၍ မိမိကိုယ်ကိုအမြဲမွမ်းမံထားရန် အကြံပြု၍၊ ပုဂ္ဂိုလ်ရေး အချက်အလက်လုံခြုံရေးဆိုင်ရာ ဤဝက်ဘ်ဆိုက်နှင့် ယင်း၏ တွဲဘက်ဆက်စပ်ဆိုက်တို့၏ပေါ်လစီတို့နှင့်စပ်လျဉ်း၍ မိမိကိုယ်ကို အမြဲမွမ်းမံထားရန် အကြံပြုတိုက်တွန်းပါသည်။

လူကြီးမင်းတို့၏ ပုဂ္ဂိုလ်ရေးဆိုင်ရာ အချက်အလက်တို့ကို ကိုင်တွယ်ဆောင်ရွက်ပြုလုပ်ပုံနှင့် စပ်လျဉ်းသည့် နောက်ထပ်သတင်းအချက်အလက်များကို ဤနေရာ တွင် ရရှိနိုင်ပါသည်။""";
